[build]
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "app.js",
    "routes/**",
    "database.js",
    "middlewares/**",
    "controllers/**",
    "models/**"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
